Build and run URP_Performance_BoatAttack_OSX_Metal_performance_playmode_editor_mono_Linear_trunk on the test MacMini

diff --git a/.yamato/urp_performance_boatattack-osx-metal.yml b/.yamato/urp_performance_boatattack-osx-metal.yml
--- a/.yamato/urp_performance_boatattack-osx-metal.yml
+++ b/.yamato/urp_performance_boatattack-osx-metal.yml
@@ -143,6 +143,7 @@ URP_Performance_BoatAttack_OSX_Metal_performance_playmode_runtime_mono_Linear_tr
             paths:
               -  "**/test-results/**"
               -  "TestProjects/BoatAttack/Logs/*.log"
+
 URP_Performance_BoatAttack_OSX_Metal_performance_playmode_editor_mono_Linear_trunk:
     name: URP_Performance_BoatAttack on OSX_Metal_performance_playmode_editor_mono_Linear on version trunk
     agent:
@@ -154,41 +155,130 @@ URP_Performance_BoatAttack_OSX_Metal_performance_playmode_editor_mono_Linear_tru
         BOAT_ATTACK_BRANCH: master
         BOAT_ATTACK_REVISION: 60b6bc595f20b29f4869d3236ce1aa91a490ef6b
     commands:
-      -  git clone https://github.com/Unity-Technologies/BoatAttack.git -b $BOAT_ATTACK_BRANCH TestProjects/BoatAttack
-      -  cd TestProjects/BoatAttack && git checkout $BOAT_ATTACK_REVISION
-      -  brew tap --force-auto-update unity/unity git@github.cds.internal.unity3d.com:unity/homebrew-unity.git
-      -  brew install unity-config
-      -  cd TestProjects/BoatAttack && unity-config project add dependency "com.unity.render-pipelines.core@file:../../../com.unity.render-pipelines.core" --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project add dependency "com.unity.render-pipelines.universal@file:../../../com.unity.render-pipelines.universal" --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project add dependency "com.unity.shadergraph@file:../../../com.unity.shadergraph" --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project add dependency com.unity.addressables@1.16.7 --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project add dependency com.unity.scriptablebuildpipeline@1.11.2 --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project add dependency com.unity.test-framework@1.1.18 --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project add dependency com.unity.test-framework.performance@2.4.0 --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project add dependency com.unity.test-framework.utp-reporter@1.0.2-preview --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project add dependency com.unity.test-framework.build@0.0.1-preview.12 --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project add dependency "com.unity.testing.graphics-performance@ssh://git@github.cds.internal.unity3d.com/unity/com.unity.testing.graphics-performance.git"  --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project add dependency "unity.graphictests.performance.universal@ssh://git@github.cds.internal.unity3d.com/unity/unity.graphictests.performance.universal.git" --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project add testable com.unity.cli-project-setup  --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project add testable com.unity.test.performance.runtimesettings  --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project add testable com.unity.test.metadata-manager  --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project add testable com.unity.testing.graphics-performance --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project add testable com.unity.render-pipelines.core  --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project add testable unity.graphictests.performance.universal  --project-path .
-      -  cd TestProjects/BoatAttack && unity-config project set project-update false --project-path .
-      -  curl -s https://artifactory.internal.unity3d.com/core-automation/tools/utr-standalone/utr --output TestProjects/BoatAttack/utr
-      -  chmod +x TestProjects/BoatAttack/utr
-      -  ssh -i ~/.ssh/id_rsa_macmini -o "StrictHostKeyChecking=no" bokken@$BOKKEN_DEVICE_IP "bash -lc 'pip3 install unity-downloader-cli --user --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple --upgrade'"
-      -  scp -i ~/.ssh/id_rsa_macmini -o "StrictHostKeyChecking=no" -r $YAMATO_SOURCE_DIR bokken@$BOKKEN_DEVICE_IP:~/Graphics
-      -  scp -i ~/.ssh/id_rsa_macmini -o "StrictHostKeyChecking=no" ~/.ssh/id_rsa_macmini bokken@$BOKKEN_DEVICE_IP:~/.ssh/id_rsa_macmini
-      -  ssh -i ~/.ssh/id_rsa_macmini -o "StrictHostKeyChecking=no" bokken@$BOKKEN_DEVICE_IP '$(/usr/local/bin/python3 -m site --user-base)/bin/unity-downloader-cli -u {{editor_versions.trunk_latest_internal.macos.revision}} -c editor -c il2cpp  --wait --published-only'
-      -  |5-
+        # Debug stuff.
+        - env | sort
 
-                 ssh -i ~/.ssh/id_rsa_macmini -o "StrictHostKeyChecking=no" bokken@$BOKKEN_DEVICE_IP "export UPM_REGISTRY=https://artifactory-slo.bf.unity3d.com/artifactory/api/npm/upm-candidates; echo \$UPM_REGISTRY; cd ~/Graphics/TestProjects/BoatAttack && ~/Graphics/TestProjects/BoatAttack/utr --artifacts_path=/Users/bokken/Graphics/TestProjects/BoatAttack/test-results --category=URP --editor-location=/Users/bokken/.Editor --extra-editor-arg="-addscenetobuild=Assets/scenes/Testing/benchmark_island-static.unity" --extra-editor-arg="-colorspace=Linear" --extra-editor-arg="-executemethod" --extra-editor-arg="Editor.Setup" --extra-editor-arg="-packageundertestbranch=$GIT_BRANCH" --extra-editor-arg="-packageundertestname=com.unity.render-pipelines.universal" --extra-editor-arg="-packageundertestrev=$GIT_REVISION" --extra-editor-arg="-packageundertestrevdate=$GIT_REVISIONDATE" --extra-editor-arg="-scriptingbackend=Mono2x" --performance-project-id=BoatAttack --report-performance-data --reruncount=2 --scripting-backend=Mono2x --suite=playmode --testproject=/Users/bokken/Graphics/TestProjects/BoatAttack"
-                 UTR_RESULT=$? 
-                 mkdir -p TestProjects/BoatAttack/test-results/
-                 scp -i ~/.ssh/id_rsa_macmini -o "StrictHostKeyChecking=no" -r bokken@$BOKKEN_DEVICE_IP:/Users/bokken/Graphics/TestProjects/BoatAttack/test-results/ TestProjects/BoatAttack/test-results/
-                 exit $UTR_RESULT
+        # Fix SSH config on the VM. The Bokken team is fixing this in the base images.
+        - sed -i '' 's/172\.28\.218\.\*/172\.28\.224\.\*/g' ~/.ssh/config
+
+        # Make SSH stuff writable.
+        - sudo chown -R bokken:staff ~/.ssh
+        - chmod u+w ~/.ssh/*
+
+        # Cleanup stuff for a Yamato Remote re-run. Only delete the source dir on the device if you really need to wipe it.
+        - ssh bokken@$BOKKEN_DEVICE_IP "rm -rf ~/.ssh/id_rsa_cds_github ~/.ssh/config ~/.utr_result"
+        - rm -rf ~/.utr_result ~/.ssh/id_rsa_cds_github
+        # - ssh bokken@$BOKKEN_DEVICE_IP "rm -rf ~/Graphics"
+
+        # Add hosts and identities to the SSH config on the VM. Comment out after the first Yamato remote run.
+        - echo >> ~/.ssh/config
+        - ls -lah ~/.ssh
+        - cat .yamato/files/ssh-config >> ~/.ssh/config
+        - scp .yamato/files/ssh-config bokken@$BOKKEN_DEVICE_IP:~/.ssh/config
+
+        # Get Github CDS SSH privkey.
+        - echo $GITHUB_CDS_SSH_PRIVKEY | base64 -D -i - -o id_rsa_cds_github
+        - scp id_rsa_cds_github bokken@$BOKKEN_DEVICE_IP:~/.ssh/id_rsa_cds_github
+        - mv id_rsa_cds_github ~/.ssh/id_rsa_cds_github
+
+        # Fix SSH stuff permissions.
+        - ssh bokken@$BOKKEN_DEVICE_IP "chmod 400 ~/.ssh/*"
+        - chmod 400 ~/.ssh/*
+
+        # Install unity-config.
+        - brew tap --force-auto-update unity/unity git@github.cds.internal.unity3d.com:unity/homebrew-unity.git
+        - brew install unity-config
+
+        # Clean any test files that may exist from previous runs.
+        - rm -rf TestProjects/BoatAttack
+
+        # Get the test project at the right revision.
+        - git clone https://github.com/Unity-Technologies/BoatAttack.git -b $BOAT_ATTACK_BRANCH TestProjects/BoatAttack
+        - cd TestProjects/BoatAttack && git checkout $BOAT_ATTACK_REVISION
+
+        # Configure project.
+        - cd TestProjects/BoatAttack && unity-config project add dependency "com.unity.render-pipelines.core@file:../../../com.unity.render-pipelines.core" --project-path .
+        - cd TestProjects/BoatAttack && unity-config project add dependency "com.unity.render-pipelines.universal@file:../../../com.unity.render-pipelines.universal" --project-path .
+        - cd TestProjects/BoatAttack && unity-config project add dependency "com.unity.shadergraph@file:../../../com.unity.shadergraph" --project-path .
+        - cd TestProjects/BoatAttack && unity-config project add dependency com.unity.addressables@1.16.7 --project-path .
+        - cd TestProjects/BoatAttack && unity-config project add dependency com.unity.scriptablebuildpipeline@1.11.2 --project-path .
+        - cd TestProjects/BoatAttack && unity-config project add dependency com.unity.test-framework@1.1.18 --project-path .
+        - cd TestProjects/BoatAttack && unity-config project add dependency com.unity.test-framework.performance@2.4.0 --project-path .
+        - cd TestProjects/BoatAttack && unity-config project add dependency com.unity.test-framework.utp-reporter@1.0.2-preview --project-path .
+        - cd TestProjects/BoatAttack && unity-config project add dependency com.unity.test-framework.build@0.0.1-preview.12 --project-path .
+        - cd TestProjects/BoatAttack && unity-config project add dependency "com.unity.testing.graphics-performance@ssh://git@github.cds.internal.unity3d.com/unity/com.unity.testing.graphics-performance.git"  --project-path .
+        - cd TestProjects/BoatAttack && unity-config project add dependency "unity.graphictests.performance.universal@ssh://git@github.cds.internal.unity3d.com/unity/unity.graphictests.performance.universal.git" --project-path .
+
+        - cd TestProjects/BoatAttack && unity-config project add testable com.unity.cli-project-setup  --project-path .
+        - cd TestProjects/BoatAttack && unity-config project add testable com.unity.test.performance.runtimesettings  --project-path .
+        - cd TestProjects/BoatAttack && unity-config project add testable com.unity.test.metadata-manager  --project-path .
+        - cd TestProjects/BoatAttack && unity-config project add testable com.unity.testing.graphics-performance --project-path .
+        - cd TestProjects/BoatAttack && unity-config project add testable com.unity.render-pipelines.core  --project-path .
+        - cd TestProjects/BoatAttack && unity-config project add testable unity.graphictests.performance.universal  --project-path .
+
+        - cd TestProjects/BoatAttack && unity-config project set project-update false --project-path .
+
+        # Get UTR into the test folder.
+        - curl -s https://artifactory.internal.unity3d.com/core-automation/tools/utr-standalone/utr --output TestProjects/BoatAttack/utr
+        - chmod +x TestProjects/BoatAttack/utr
+
+        # Upload the Graphics repo to the device or update it. The folder will be at ~/Graphics in the remote. Ignore dot files to keep it snappy (especially for Yamato Remote).
+        - rsync -uaqP --exclude=".*" --inplace $YAMATO_SOURCE_DIR bokken@$BOKKEN_DEVICE_IP:~/
+
+        # Install the Unity Downloader.
+        - ssh bokken@$BOKKEN_DEVICE_IP "bash -lc 'pip3 install unity-downloader-cli --user --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple --upgrade'"
+
+        # Get the Editor and required components for the project. This will be rendered as a single line command. Beware of the quotes! They bite, repeatedly. :(
+        - >
+            ssh bokken@$BOKKEN_DEVICE_IP
+            "\$(/usr/local/bin/python3 -m site --user-base)/bin/unity-downloader-cli    \\
+                -u {{editor_versions.trunk_latest_internal.macos.revision}}             \\
+                -c editor                                                               \\
+                -c il2cpp                                                               \\
+                --wait                                                                  \\
+                --published-only"
+
+        # Run build/tests on the device and capture exit code. This will be rendered as a single line command. Beware of the backslashes and the semicolons too.
+        - >
+            ssh bokken@$BOKKEN_DEVICE_IP
+            "export UPM_REGISTRY=$UPM_REGISTRY;
+            echo ==================================================;
+            echo UPM Registry: \$UPM_REGISTRY;
+            echo ==================================================;
+            cd ~/Graphics/TestProjects/BoatAttack/;
+            ./utr                                                                                           \\
+                --artifacts_path=/Users/bokken/Graphics/TestProjects/BoatAttack/test-results                \\
+                --category=URP                                                                              \\
+                --editor-location=/Users/bokken/.Editor                                                     \\
+                --extra-editor-arg="-addscenetobuild=Assets/scenes/Testing/benchmark_island-static.unity"   \\
+                --extra-editor-arg="-colorspace=Linear"                                                     \\
+                --extra-editor-arg="-executemethod"                                                         \\
+                --extra-editor-arg="Editor.Setup"                                                           \\
+                --extra-editor-arg="-packageundertestbranch=$GIT_BRANCH"                                    \\
+                --extra-editor-arg="-packageundertestname=com.unity.render-pipelines.universal"             \\
+                --extra-editor-arg="-packageundertestrev=$GIT_REVISION"                                     \\
+                --extra-editor-arg="-packageundertestrevdate=$GIT_REVISIONDATE"                             \\
+                --extra-editor-arg="-scriptingbackend=Mono2x"                                               \\
+                --performance-project-id=BoatAttack                                                         \\
+                --platform=StandaloneOSX                                                                    \\
+                --report-performance-data                                                                   \\
+                --reruncount=2                                                                              \\
+                --scripting-backend=Mono2x                                                                  \\
+                --suite=playmode                                                                            \\
+                --testproject=/Users/bokken/Graphics/TestProjects/BoatAttack;
+            echo \$? > ~/.utr_result"
+        # Read UTR result and data from test device.
+        - scp bokken@$BOKKEN_DEVICE_IP:~/.utr_result ~/.utr_result
+        - rsync -aqP bokken@$BOKKEN_DEVICE_IP:~/Graphics/TestProjects/BoatAttack/test-results $YAMATO_SOURCE_DIR/TestProjects/BoatAttack/
+
+        # Print status and exit with UTR's exit code.
+        - |
+            UTR_RESULT=$(cat ~/.utr_result)
+            echo "=================================================="
+            echo "UTR exit code: $UTR_RESULT"
+            echo "=================================================="
+            exit $UTR_RESULT
+
     artifacts:
         logs:
             paths:
